apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-app-rs
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: 497449888023.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1:my_app_latest
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-service"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: dbuser
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: dbpassword
        - name: DBNAME
          value: "mydatabase"
