apiVersion: v1
kind: Pod
metadata:
  name: web-app
spec:
  containers:
  - name: web-app
    image: 497449888023.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1:my_app_latest
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: ecr-registry-secret
