apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  containers:
  - name: web-app
    image: 497449888023.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1/web-app:latest
    ports:
    - containerPort: 8080
