apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 497449888023.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1:my_db_latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "dbpassword"
        ports:
        - containerPort: 3306
